/*
  # Create BD Relationship Layer (V1)

  This migration creates the minimal BD relationship foundation:
  - public.companies (defensive `if not exists` to avoid duplicating an existing remote table)
  - public.bd_contacts (hiring-side contacts linked to companies)

  Notes:
  - Additive only.
  - RLS enabled with read-only SELECT policies for anon/authenticated, matching current app anon-key usage.
  - No INSERT/UPDATE policies yet (imports should use service-role).
*/

-- NOTE: public.companies already exists in the current Supabase project.
-- This `if not exists` block makes fresh environments consistent without
-- conflicting with an existing table.
create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  company_name text,
  company_slug text,
  website_url text,
  linkedin_url text,
  hq_country text,
  primary_city text,
  company_status text,
  source_type text,
  notes text,
  updated_at timestamptz
);

create table if not exists public.bd_contacts (
  id uuid primary key default gen_random_uuid(),
  company_id bigint references public.companies(id) on delete set null,
  full_name text not null,
  first_name text,
  last_name text,
  email text,
  phone text,
  mobile_phone text,
  job_title text,
  department text,
  relationship_status text default 'new',
  contact_type text default 'client_contact',
  source text default 'legacy_bd_list',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists bd_contacts_company_id_idx on public.bd_contacts using btree (company_id);
create index if not exists bd_contacts_relationship_status_idx on public.bd_contacts using btree (relationship_status);
create index if not exists bd_contacts_email_idx on public.bd_contacts using btree (email);
create unique index if not exists bd_contacts_email_uniq
  on public.bd_contacts using btree (email)
  where email is not null and length(trim(email)) > 0;

alter table public.bd_contacts enable row level security;

create policy "Anon users can read bd_contacts"
  on public.bd_contacts for select to anon
  using (true);

create policy "Authenticated users can read bd_contacts"
  on public.bd_contacts for select to authenticated
  using (true);
